.TH TOMOTKO "1" "January 2009" "toMOTko 0.11.2" "Manual page"
.SH NAME
toMOTko \- a flashcard learning software
.SH SYNOPSIS
.B toMOTko
.SH DESCRIPTION
toMOTko is a program written in QT in order to learn foreign languages based on
a flashcard system.
.SH COPYRIGHT
Copyright \(co 2006-2009, Frederic Bergeron
.SH "SEE ALSO"
http://tomotko.sourceforge.net/
